Bonus entity, repository and service have been created.
Valentine1996/FamilyTime pull request #35
Opened 2016-09-18 19:41 UTC by andrycreator

2016-09-19 07:42 UTC, vtsutsman commented on src/main/java/com/familytime/model/service/implementation/BonusImpl.java
> +public class BonusImpl implements BonusService {
@andrycreator rename `BonusImpl` to `BonusServiceImpl`.

2016-09-19 07:43 UTC, vtsutsman commented on src/main/java/com/familytime/model/service/implementation/BonusImpl.java
> +        return null;
@andrycreator Why do U return `null`?

2016-09-19 07:44 UTC, vtsutsman commented on src/main/java/com/familytime/model/service/implementation/BonusImpl.java
> +
@andrycreator Add implementation.

2016-09-19 07:45 UTC, vtsutsman commented on src/main/java/com/familytime/model/service/implementation/BonusImpl.java
> +public class BonusImpl implements BonusService {
@andrycreator Here should be annotation `@Service`

2016-09-19 07:46 UTC, vtsutsman commented on src/main/java/com/familytime/model/repository/BonusRepository.java
> +@Transactional
@andrycreator U should not use `@Transactional` on the `repository` level.

2016-09-19 07:49 UTC, vtsutsman requested changes
Add implementation of service's methods.
Use `@Transactional` only in `service` layer.

2016-09-19 21:20 UTC, andrycreator commented on src/main/java/com/familytime/model/service/implementation/BonusImpl.java
> +public class BonusImpl implements BonusService {
The changes have been done.

2016-09-19 21:22 UTC, andrycreator commented on src/main/java/com/familytime/model/service/implementation/BonusImpl.java
> +public class BonusImpl implements BonusService {
The changes have been done.

2016-09-19 21:24 UTC, andrycreator commented on src/main/java/com/familytime/model/service/implementation/BonusImpl.java
> +        return null;
The changes have been done.

2016-09-19 21:28 UTC, andrycreator commented on src/main/java/com/familytime/model/service/implementation/BonusImpl.java
> +
The changes have been done.

2016-09-19 21:34 UTC, andrycreator commented on src/main/java/com/familytime/model/repository/BonusRepository.java
> +@Transactional
The changes have been done.

2016-09-20 21:26 UTC, andrycreator commented
All changes have been done, please take a look.

2016-09-21 08:57 UTC, vtsutsman approved these changes
Looks good to me.

2016-09-21 08:58 UTC, vtsutsman approved these changes

2016-09-21 09:32 UTC, Valentine1996 approved these changes

2016-09-21 09:32 UTC, merged