Password recovery
Valentine1996/FamilyTime pull request #37
Opened 2016-09-19 20:56 UTC by Valentine1996

#12

2016-09-20 07:54 UTC, vtsutsman commented on src/main/resources/config/mail/config.properties
> +email.host=localhost
@Valentine1996 Why do U need these vars?

2016-09-20 07:55 UTC, vtsutsman commented on src/main/java/com/familytime/security/model/service/implementtion/AccessRecoveryServiceImpl.java
> +    public void restore( String hash, String password ) {
@Valentine1996 I believe U need `@Transactional` here.

2016-09-20 07:58 UTC, vtsutsman requested changes
Add transactions management.

2016-09-21 09:57 UTC, vtsutsman approved these changes

2016-09-21 09:59 UTC, coffeine-009 approved these changes

2016-09-21 09:59 UTC, merged