Create entity, service and repository for table Task
Valentine1996/FamilyTime pull request #39
Opened 2016-10-04 20:37 UTC by andrycreator

The entity, service and repository for table Task have been done.

2017-01-22 11:02 UTC, coffeine-009 commented
@andrycreator This PR brakes tests. You should fix tests.
```bash
7 tests completed, 6 failed, 1 skipped
:test FAILED
```
See travis-ci report.

2017-01-22 11:03 UTC, coffeine-009 requested changes

2017-01-22 11:03 UTC, coffeine-009 commented on config/checkstyle/checkstyle.xml
> +            <property name="max" value="115"/>
@andrycreator You should fix code. Changing code style is not a good idea.

2017-01-22 11:03 UTC, coffeine-009 commented on src/test/java/com/familytime/controller/HelloRestControllerTest.java
> +import org.junit.Ignore;
Why do you need @Ignore if you do not use it?

2017-01-22 11:03 UTC, coffeine-009 commented on src/test/java/com/familytime/model/service/NotificationServiceTest.java
> +import org.junit.Ignore;
Why do you need @Ignore if you do not use it?

2017-01-22 11:03 UTC, coffeine-009 commented on src/test/java/com/familytime/security/SecurityControllerTest.java
> +import org.junit.Ignore;
Why do you need @Ignore if you do not use it?

2017-01-22 11:03 UTC, coffeine-009 commented on src/main/java/com/familytime/model/entity/Task.java
> +    @Value("#{LocalDateTime.now}")
@andrycreator It would be better to use JPA for setting current date&time.
Use JPA annotation `@PrePersist`.

2017-01-26 22:41 UTC, andrycreator commented on src/main/java/com/familytime/model/entity/Task.java
> +    @Value("#{LocalDateTime.now}")
I tried to use @PrePersist but I've got message that it is not applicable to field.

2017-01-27 21:59 UTC, coffeine-009 commented on src/main/java/com/familytime/model/entity/Task.java
> +    @Value("#{LocalDateTime.now}")
U should create method
```java
@PrePersist
public preStore() {
    this.createdAt = ...
}
```

2017-01-30 22:13 UTC, closed without merging